# workflow to clean github workflow runs for my repositories

name: Github WF Runs Clean
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

jobs:
  gha_clean:
    runs-on: ubuntu-latest
    name: Github WF Runs Clean
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: check self
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/github_actions_clean -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }} -c 1
    - name: check a2c
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/acme2certifier -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
    - name: check est_proxy
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/est_proxy -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
    - name: check dkb-robo
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/dkb-robo -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
    - name: check grindsa/ncm-issuer
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/ncm-issuer -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
    - name: check grindsa/sbom
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/sbom -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
    - name: check grindsa/my_playground
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/my_playground -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }} -c 1
    - name: check grindsa/delstat_scraper
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/delstat_scraper -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }} -c 1

    - name: check grindsa/delapp_helper
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/delapp_helper -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }} -c 1

    - name: check grindsa/docker-pen
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/docker-pen -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }} -c 1

    - name: check nokia/ncm-issuer
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r nokia/ncm-issuer -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 1
