# workflow to clean github workflow runs for my repositories

name: Github WF Runs Clean
on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  gha_clean:
    runs-on: ubuntu-latest
    name: Github WF Runs Clean
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: check self
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/github_actions_clean -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}
    - name: check a2c
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/acme2certifier -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
    - name: check est_proxy
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/est_proxy -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
    - name: check dkb-robo
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/dkb-robo -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
    - name: check grindsa/ncm-issuer
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r grindsa/ncm-issuer -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
    - name: check nokia/ncm-issuer
      run: |
        python3 ./gh_workflow_runs_delete.py -d  -r nokia/ncm-issuer -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
