# workflow to clean github actions for my repositories

name: Github Action Clean
on:
  push:  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * 6'

jobs:
  gha_clean:
    runs-on: ubuntu-latest
    name: Github Action Clean
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: check a2c
      run: |
        python3 ./github_actions_clean.py -d  -r grindsa/acme2certifier -t ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}  -c 2
